name: "Package App"
description: "Builds JS bundles and packages the Electron application"
runs:
  using: "composite"
  steps:
    - name: Build JS sources
      shell: bash
      run: npm run build
    - name: Rebuild native dependencies for Electron
      shell: bash
      run: npx electron-builder install-app-deps
    - name: Package Application
      shell: bash
      run: npx electron-builder --publish never
