name: "Setup and Test"
description: "Sets up Node, installs dependencies, and runs E2E tests"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      shell: bash
      run: npm ci
    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps
    - name: Run E2E Tests
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npm run test:e2e
        else
          npm run test:e2e
        fi
